package filmesdb.usjt.br.filmesdb.model;

import java.util.ArrayList;

public class FilmeDAO {
    private static ArrayList<Filme> filmes;

    public FilmeDAO() {}

    public static ArrayList<Filme> getFilmes() {
        if (filmes == null) {
            filmes = new ArrayList<>();

            filmes.add(new Filme(1, "Batman - O Cavaleiro das Trevas Ressurge", "Ação", "Passaram-se oito anos desde que Batman desapareceu na noite, e naquele instante passou de herói a vilão. Ao assumir a culpa pela morte do promotor Harvey Dent, o Cavaleiro das Trevas sacrificou tudo o que era importante para ele, e agora sofre uma perseguição liderada por seu amigo Comissário Gordon. Agora, ele terá de lidar com a chegada de um ladrão muito esperto e misterioso. Muito mais perigoso, no entanto, é o aparecimento de Bane, um terrorista mascarado, cujo plano é tirar Bruce desse exílio auto-imposto.","Christopher Nolan", "27/07/2012", 4.2));
            filmes.add(new Filme(2, "Ex Machina - Instinto Artificial", "Ficção Científica", "Em um refúgio nas montanhas de um talentoso bilionário da internet, um jovem participa de uma estranha experiência: testar a inteligência artificial, inserida no corpo de uma bela garota robô. Mas a experiência se torna uma sinistra batalha psicológica: um triângulo amoroso, onde a lealdade está dividida entre homem e máquina.", "Alex Garland", "06/08/2015", 3.9));
            filmes.add(new Filme(3, "Uma Mente Brilhante", "Drama", "Uma Mente Brilhante é baseado no livro A Beautiful Mind: A Biography of John Forbes Nash Jr., de Sylvia Nasar. O filme conta a história real de John Nash que, aos 21 anos, formulou um teorema que provou sua genialidade. Brilhante, Nash chegou a ganhar o Prêmio Nobel. Diagnosticado como esquizofrênico pelos médicos, Nash enfrentou batalhas em sua vida pessoal, lutando até o fim de sua vida.", "Ron Howard", "15/02/2002", 4.3));
            filmes.add(new Filme(4, " A Chegada", "Mistério", "Quando seres interplanetários deixam marcas na Terra, a Dra. Louise Banks (Amy Adams), uma linguista especialista no assunto, é procurada por militares para traduzir os sinais e desvendar se os alienígenas representam uma ameaça ou não. No entanto, a resposta para todas as perguntas e mistérios pode ameaçar a vida de Louise e a existência de toda a humanidade.", "Denis Villeneuve", "14/11/2016", 4.2));
            filmes.add(new Filme(5, "Kill Bill: Volume 1", "Ação", "No dia de seu casamento, a Noiva (Uma Thurman), uma perigosa assassina profissional, é espancada pelos membros do grupo de extermínio de que fazia parte. Bill, o chefe do grupo, atira em sua cabeça, o que a coloca em coma por quatro anos. Ao despertar, ela tem único desejo: vingança.", "Quentin Tarantino", "23/04/2004", 4.2));
            filmes.add(new Filme(7, "Missão: Impossível - Protocolo Fantasma", "Aventura", "O agente Ethan Hunt (Tom Cruise) e seu grupo de elite vão parar no submundo, depois que uma explosão no Kremlin incrimina IMF como terroristas internacionais. Ao tentar limpar a reputação da agência, o grupo descobre um plano para começar uma guerra nuclear. Agora, para salvar o mundo, eles precisam usar todos os truques tecnológicos existentes. A missão nunca foi tão real, tão perigosa, nem tão impossível.", "Brad Bird", "23/12/2011", 3.7));
            filmes.add(new Filme(6, "Interestelar", "Aventura", "Após ver a Terra consumindo boa parte de suas reservas naturais, um grupo de astronautas recebe a missão de verificar possíveis planetas para receberem a população mundial, possibilitando a continuação da espécie. Cooper (Matthew McConaughey) é chamado para liderar o grupo e aceita a missão sabendo que pode nunca mais ver os filhos. Ao lado de Brand (Anne Hathaway), Jenkins (Marlon Sanders) e Doyle (Wes Bentley), ele seguirá em busca de uma nova casa. Com o passar dos anos, sua filha Murph (Mackenzie Foy e Jessica Chastain) investirá numa própria jornada para também tentar salvar a população do planeta.", "Christopher Nolan", "06/11/2014", 4.3));
            filmes.add(new Filme(8, "Os Incríveis", "Animação", "Beto Pêra e sua mulher Helena estavam entre os maiores super-heróis do mundo, salvando vidas e combatendo o mal diariamente. Quinze anos depois, eles foram forçados a adotar novas identidades e a mudar-se para o subúrbio, onde vivem como cidadãos comuns com seus três filhos, Violeta, Flecha e Zezé. Louco para voltar à ação, Beto tem a sua chance quando uma misteriosa ligação o intima a comparecer a uma ilha distante para receber uma missão ultrassecreta. Ele logo descobre que só uma família inteira de super-heróis será capaz de salvar o mundo e impedir sua total destruição.", "Brad Bird", "10/12/2004", 3.8));
            filmes.add(new Filme(9, "O Abutre", "Drama", "Lou Bloom (Jake Gyllenhaal) é um jovem determinado e desesperado por trabalho que descobre o mundo em alta velocidade do jornalismo sensacionalista em Los Angeles. Ao encontrar equipes de filmagem freelances à caça de acidentes, incêndios, assassinatos e outras desgraças, Lou entra no reino perigoso e predatório dos nightcrawlings - as minhocas que só saem da terra à noite.", "Dan Gilroy", "18/12/2014", 4.0));
            filmes.add(new Filme(10, "O Poderoso Chefão", "Drama", "Em 1945, Don Corleone (Marlon Brando) é o chefe de uma mafiosa família italiana de Nova York. Ele costuma apadrinhar várias pessoas, realizando importantes favores para elas, em troca de favores futuros. Com a chegada das drogas, as famílias começam uma disputa pelo promissor mercado. Quando Corleone se recusa a facilitar a entrada dos narcóticos na cidade, não oferecendo ajuda política e policial, sua família começa a sofrer atentados para que mudem de posição. É nessa complicada época que Michael (Al Pacino), um herói de guerra nunca envolvido nos negócios da família, vê a necessidade de proteger o seu pai e tudo o que ele construiu ao longo dos anos.", "Francis Ford Coppola", "07/07/1972", 4.7));
        }

        return filmes;
    }
}
